git commit -m "first commit"
HannelizeHuman/EventFinder_Impulse pull request #29
Opened 2021-04-13 11:13 UTC by Jose109-001

2021-04-13 11:24 UTC, HannelizeHuman commented on restaurant.html
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet">
This link needs to change to the link Bootstrap link both Brendan and myself used
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">`

2021-04-13 11:25 UTC, HannelizeHuman commented on restaurant.html
> +    <title>Impulse</title>
The title for this should be Resturants

2021-04-13 11:26 UTC, HannelizeHuman commented on restaurant.html
> +      <img src="./assets/images/navlogo.png" alt="Impulse"  class="d-inline-block align-text-top">
The image should be the new logo Brendan made called: 1_transparent.png

2021-04-13 11:27 UTC, HannelizeHuman commented on restaurant.html
> +        <li><a href="tickets.html">Events</a></li>
This should be events.html

2021-04-13 11:29 UTC, HannelizeHuman commented on assets/css/restaurant.css
> +  }
Check the Styling from Brendan's event.html and Michael's event.css 
Because you won't need all of this if you're using Bootstrap

2021-04-13 11:30 UTC, HannelizeHuman requested changes
Check comments made next to code for changes that need to be made.

2021-04-15 08:29 UTC, HannelizeHuman approved these changes

2021-04-15 08:30 UTC, HannelizeHuman approved these changes

2021-04-15 09:48 UTC, HannelizeHuman commented on restaurant.html
> +                        <a class="nav-link" href="events.html">Events</a>
Just check this needs to be `event.html` 
otherwise it won't link

2021-04-15 09:50 UTC, HannelizeHuman requested changes
Just need to change the `events.html` to `event.html`
Line 37 of your HTML file

2021-04-15 10:35 UTC, closed without merging

2021-04-15 10:35 UTC, Jose109-001 commented
test